### ISSUE TITLE
l function doesn't translate back to default lang & l & t functions ts error on generic string argument with generated types and astroI18n object has no generated types

### ISSUE THREAD

**Issue by narduin** [Alexandre-Fernandez/astro-i18n#1]
Hello!

First of all a huge thank you for this plugin. I've been searching and trying to make a multilingual astro site for months!
This is by far the simplest way to make i18n work with astro so again, thanks a lot!

---

Now, I've been trying to implement a way to switch the language of a website from a link in the header, and be taken to the equivalent page in another locale.

I feel like I'm almost there but can't figure out the last part. So far, what's missing is the ability to get the current route name and to navigate to its other languages alternatives.

<details>
<summary>Here is my component</summary>

```astro
---
// LanguageSwitcher.astro

import { l, astroI18n } from "astro-i18n";

// get the locale currently in use
const currentLocale = astroI18n.langCode;
// get all the locales available on the website and remove the one currently in use
const availableLocales = astroI18n.langCodes.filter(
	(locale) => locale !== currentLocale
);
---

<ul>
	{
		// create a list of available alternative locales
		availableLocales.map((locale) => (
			<li>
				// first parameter is supposed to be a dynamic route name
				<a href={l("/", {}, "", locale)}>{locale}</a>
			</li>
		))
	}
</ul>
```

</details>

Using a static route like `/articles` and having two locales `fr` (default) and `en` is working. I can switch from `/articles` to `/en/blog` and vice versa. I just can't find a way to do it dynamically.

Also, I can't make it work for the root index page with `/`

<details>
<summary>I'm using the folder structure for i18n implementation</summary>

```bash
index.astro
i18n
  en.json
  fr.json
articles
  index.astro
  i18n
    en.json
    fr.json
```

</details>

Maybe this is not something this module is supposed to be doing, I'm coming from [nuxt-i18n](https://github.com/nuxt-modules/i18n) where I was able to use a function to navigate to the page:

<details>
<summary>switchLocalePath()</summary>

```vue
<nuxt-link
	v-for="locale in availableLocales"
	:key="locale.code"
	:to="switchLocalePath(locale.code)"
	class="nice-link"
	>
  {{ locale.name }}
</nuxt-link>
```

</details>

Any idea on how to make this work?
Thanks!

**Comment by Alexandre-Fernandez** [comment]
Thanks, I didn't include a language switch component because it was difficult to make one that would fit everyone needs.
Here's how you can do it :
```ts
const urls = astroI18n.langCodes
	.filter(langCode => langCode !== astroI18n.langCode) // optional
	.map(langCode => l(Astro.url.pathname as any, {}, {}, langCode as any))
```
However as you can see, with my generated types, I had to use `any`. I didn't think of this scenario when generating the types, I will try to fix when I get some time.

**Comment by narduin** [comment]
Thank you for this!
I had tried with `Astro.url.pathname` but thought it was not the right thing to use because translated routes like `articles` in french becoming `blog` in english would not work. Once on `/en/blog`, I can't go back to `/articles`, only to `/blog`.
I guess I need to keep `articles` for both 😄 

However, your example throws an error when trying to access the root index `/en`. I had the same error in some trials I made, don't really know why though…

```log
Cannot read properties of undefined (reading 'endsWith')
/node_modules/.pnpm/astro-i18n@1.1.7/node_modules/astro-i18n/dist/src/index.mjs:13:8731
```

**Comment by Alexandre-Fernandez** [comment]
I'm looking into the error, I managed to reproduce it.
As for the first part of your comment, I didn't understand what you mean. The `l` function should translate `/fr/articles` into `/en/blog`, if that's the translation you have set in your `routeTranslations`.

**Comment by narduin** [comment]
I tried having my route translations inside `routeTranslations` as well as in `en.json` with 

```json
"{route}": "blog"
```

But I'm getting the same result:

1. from root index `/` -> `/articles`
2. from `/articles` -> `/en/blog`
3. from `/en/blog` -> `/blog` which is a 404

I'm going to make a small repo available for reproduction for you (and to see if it's not coming from an error eslwhere in my code).

**Comment by Alexandre-Fernandez** [comment]
I found where the error comes from I will try to fix it today since it's pretty urgent.
Concerning the route translations assuming `en` is your `defaultLangCode` :
Using astro.config file :
```ts
{
  defaultLangCode: "en"
  supportedLangCodes: ["fr"],
  routeTranslations: {
    fr: {
      blog: "articles"
    }
  }
}
```
Using page routeTranslations:
```ts
// pages/en/blog/i18n/fr.json
{
  "{route}": "articles"
}
```
Did you it like this ?

**Comment by Alexandre-Fernandez** [comment]
I just patched this error out, thanks for reporting.
```
Cannot read properties of undefined (reading 'endsWith')
/node_modules/.pnpm/astro-i18n@1.1.7/node_modules/astro-i18n/dist/src/index.mjs:13:8731
```

**Comment by narduin** [comment]
Hey, I made a [small codesandbox reproduction](https://codesandbox.io/p/sandbox/gifted-christian-swmcb9) of my problem. I can add you as editor if you provide an email (privately of course).

- You can navigate to the `/en` root index but can't go back to the `fr`.
- You can navigate to `/articles` and switch to `/en/blog` but can't go back to `articles`, the link becomes `/blog`.

I hope I did not make a mess with the configuration. Initially, I had the `<I18nProvider>` only in my template. I tried to use it inside pages and components but no luck…

**Comment by Alexandre-Fernandez** [comment]
> You can navigate to the /en root index but can't go back to the fr.

I fixed this in 1.1.9.

> You can navigate to /articles and switch to /en/blog but can't go back to articles, the link becomes /blog.

I'm looking into this.

**Comment by narduin** [comment]
I used to put `<I18nProvider>` in the layout around all the html but it made some weird auto-formating when saving.
I tried putting it around the body but the bug persists.
Am I not supposed to put it in the layout?

**Comment by Alexandre-Fernandez** [comment]
I fixed the typescript issues in 1.2.0.
Concerning the `/blog` issue, it's happening because right now the `l` function doesn't translate back to the default language. This is an oversight and will be fixed as soon as possible.

**Comment by narduin** [comment]
Thanks a lot for all this, it's awesome!

**Comment by Alexandre-Fernandez** [comment]
Fixed in 1.3.0, don't hesitate to report any further bugs if you find any.
I removed the query string argument from the `l` function I added a helper to replace it instead: `appendQueryString`.
